# Makefile for compiling Atomsk and
# linking statically.
# All defaults are used (see main Makefile)
# except the compilation flags, defined below.

# USAGE:
#    make -f Makefile.static all

export

# Define compiler flags for static compilation
FORTRAN=gfortran -z muldefs
FFLAGS=-O2 -fno-backslash -I..$(SEP)$(OBJ) -J..$(SEP)$(OBJ) -static -fPIC
LAPACK=-llapack -lblas

# Goto main Makefile
include Makefile
